「lsコマンドを作る2」の課題である-aオプションが使えるlsコマンドを実装
cellotak/ruby-practices pull request #7
Opened 2023-07-28 05:30 UTC by cellotak

[lsコマンドを作る2 \| FBC](https://bootcamp.fjord.jp/practices/222)の課題に対応した、-aオプションが使えるlsコマンドを実装しました。

ただし、-aオプションの後にディレクトリ指定すると動作しなくなるため、修正が必要です。
例
``` bash
$ ruby ls.rb /home/cellotak -a      #これはOK
$ ruby ls.rb -a /home/cellotak      #これはNG    
```

NGの原因としては、ディレクト名の引数の受け取り方を
```ruby
target_path = ARGV[0] || './'
```
としていることで、先に`-a`を読み込むとARGB[0]がディレクトリ名ではなく`-a`となってしまうからです。どちらにも対応できる方法を模索中です。

2023-07-31 06:09 UTC, cellotak commented on 04.ls/ls.rb
>  target_path = ARGV[0] || './'
現在コマンドライン引数でディレクトリ指定した際に、`ARGV[0]`をそのディレクトリ名として使用しているため、オプション自体に引数がある場合や、そのほかに引数があった場合に対応できません。
しかしまだオプションを増やしていく段階ですので、ここはこのままにして最終的に対応できるように変更したいと考えています。

2023-07-31 06:09 UTC, cellotak commented on 04.ls/ls.rb
> +  widths = filenames_table.map { |col| col.map(&:size).max + SPACE_WIDTH }
引数で引いてきた`filenames`と
`filenames_table`の中身としての`filenames`
が名前被りしていたので後者を`col` と変更しました。
実態は列の要素そのものなので`col`で問題ないと考えました。
前回は 35行目の処理の部分で
```ruby
filenames_table[col][row]
```
としていて、列そのものの配列としての`col`と、列番号を表す数値としてのcolが同じ名前でわかりづらいという指摘を頂いたので

```ruby
filenames_table[col_index][row_index]
```
として、列番号としての`col`は`col_index`とすることで混乱を避けるようにしてあります。

2023-07-31 08:39 UTC, kazzbps commented
PRのdescriptionには、今回実装した機能を実行するとどうなるかを書くとよいと思います

* `./ls -a`

```
.   .gitignore  ls.rb  
..  .gitkeep    
```

* `./ls -a ..`

```
.             01.fizzbuzz  06.bowling_object  
..            02.calendar  07.ls_object       
.git          03.bowling   98.rake            
.gitignore    04.ls        99.wc_object       
.rubocop.yml  05.wc        README.md        
```

2023-07-31 08:57 UTC, cellotak commented
> PRのdescriptionには、今回実装した機能を実行するとどうなるかを書くとよいと思います
> 
> * `./ls -a`
> 
> ```
> .   .gitignore  ls.rb  
> ..  .gitkeep    
> ```
> 
> * `./ls -a ..`
> 
> ```
> .             01.fizzbuzz  06.bowling_object  
> ..            02.calendar  07.ls_object       
> .git          03.bowling   98.rake            
> .gitignore    04.ls        99.wc_object       
> .rubocop.yml  05.wc        README.md        
> ```

2023-07-31 09:15 UTC, kazzbps commented on 04.ls/ls.rb
>  target_path = ARGV[0] || './'
今回 optparse を採用したということなとので、 optparse の基本的な使い方をもう少し把握されるとよいと思います

https://docs.ruby-lang.org/ja/latest/library/optparse.html
の概要

![image](https://github.com/cellotak/ruby-practices/assets/24219290/b5eac2cc-98e9-45d9-9deb-59c91edb08bf)


`OptionParser#parse!` の戻り値は、オプションを除いた要素になり、引数に指定したファイル名(ディレクトリ名)を取得できることになります

optparse は、引数のオプションのみを得るのではなく、引数の非オプションと指定されたオプションの両方を取得できるライブラリになるかと思います

ということで、optparse を使うと `ARGV[0]` ではなく、
parse!(ARGV) でオプションを含まない指定されたファイル(ディレクトリ)名が得られるようになると思いますので
オプションの追加より、複数ファイル指定ができない等の問題を解決するのがよいかなと思います

2023-07-31 09:32 UTC, cellotak commented
@kazzbps 
descriptionについて承知しました。
一応FBCの提出フォームの方で、スクリーンショットともに機能説明をしていますが、PRだけ見る方も想定して書こうと思います。

2023-07-31 10:00 UTC, cellotak commented on 04.ls/ls.rb
>  target_path = ARGV[0] || './'
@kazzbps 
もしかすると少し行き違いになっているかもしれませんが、
既に13行目で`opt.parse!(ARGV)`を使ってARGVからオプションを取り除けています。
ですのでオプションおよび1つ以下のディレクトリ指定があった場合は順不同で動作します。

ただし、オプションに紐づいた引数 (例えば`-T`オプションはタブ幅を8の代わりに引数の数字にする)　があった場合や、オプション以外の引数が2つ以上あった場合には現在対応していない、という意味で、この説明をしていました。

もし的はずれなコメントでしたらすみません。　

2023-07-31 21:17 UTC, kazzbps commented on 04.ls/ls.rb
>  target_path = ARGV[0] || './'
コメントありがとうございます。

43行目の `ARGV[0]` は search_options の副作用でオプション引数が消えているので、引数に最初に指定されたディレクトリ名となり、ディレクトリ名の複数指定は今はやらないと理解しました

`target_path` という変数名ですが、`current_path` の方がニュアンスが近いのかもと思いました
※ ls は ファイル名も引数にとれますが、ファイル名の引数指定は未対応という理解です

2023-07-31 21:47 UTC, kazzbps requested changes
ファイル数の少ないディレクトリを指定するとエラーが出るようなのでご確認お願いします

2023-07-31 21:47 UTC, kazzbps commented on 04.ls/ls.rb
> +      target_filename = filenames_table[col_index][row_index]
filenames が 3(=NUMBER_OF_COL) を下回る場合にエラーが出ると思われます

具体的には以下のようになります

```
> ls one
1.txt

> ./ls.rb one
1.txt  ./ls.rb:35:in `block (2 levels) in output': undefined method `[]' for nil:NilClass (NoMethodError)

      target_filename = filenames_table[col_index][row_index]
                                                  ^^^^^^^^^^^
```

2023-07-31 21:47 UTC, kazzbps commented on 04.ls/ls.rb
>    filenames_table = filenames.each_slice(number_of_row).to_a
filenames が 空配列の場合エラーが発生すると思います

具体的には空ディレクトリを指摘すると以下のようになります

```
> ls empty

> ./ls.rb empty
./ls.rb:28:in `each_slice': invalid slice size (ArgumentError)
```

2023-07-31 21:47 UTC, kazzbps commented on 04.ls/ls.rb
>    filenames_table = filenames.each_slice(number_of_row).to_a
このコメントの意図がつかみかねていましたが、 lsの折り返しは転置されるのですね
(恥ずかしながら知らなかった...

```
> ls eight
1.txt    4444.txt    7777777.txt
22.txt   55555.txt   88888888.txt
333.txt  666666.txt
```

上記を each_slice(3) すると

```ruby
[
  [      "1.txt",       "22.txt",    "333.txt"],
  [   "4444.txt",    "55555.txt", "666666.txt"], 
  ["7777777.txt", "88888888.txt"]
]
```

となるので、これを行ごと(上から)ではなく列ごと(左から)に読む戦略と理解しました

2023-08-01 05:51 UTC, cellotak commented on 04.ls/ls.rb
>  target_path = ARGV[0] || './'
> target_path という変数名ですが、current_path の方がニュアンスが近いのかもと思いました

ディレクトリ名を指定した際はcurrentディレクトリではないpath名が入るのですが、その点踏まえても`current_path`の方が合っていますでしょうか。


> ※ ls は ファイル名も引数にとれますが、ファイル名の引数指定は未対応という理解です

その通りです。

2023-08-01 05:52 UTC, cellotak commented on 04.ls/ls.rb
> +      target_filename = filenames_table[col_index][row_index]
バグを見つけていただきありがとうございます。
filenames が 3(=NUMBER_OF_COL) を下回る場合でも表示できるように修正しました。

2023-08-01 05:53 UTC, cellotak commented on 04.ls/ls.rb
>    filenames_table = filenames.each_slice(number_of_row).to_a
こちらもご指摘ありがとうございます。
filenamesが空の時はoutputの処理を行わないという方法でエラーを回避するよう修正しました。

2023-08-01 05:56 UTC, cellotak commented on 04.ls/ls.rb
>    filenames_table = filenames.each_slice(number_of_row).to_a
いきなり見ると、lsコマンドが転置して表示する仕様になっていることに気づきづらいですね。
その背景がわかるように一応コメント追記しておきました。

2023-08-01 06:27 UTC, kazzbps commented on 04.ls/ls.rb
> +      target_filename = filenames_table[col_index][row_index]
修正確認しました 👍

2023-08-01 06:39 UTC, kazzbps approved these changes
バグ修正確認しました

空配列のガードに関して見直してみましょう

2023-08-01 06:39 UTC, kazzbps commented on 04.ls/ls.rb
> +output(filenames) unless filenames.empty?
空フォルダ指定時のエラー修正確認しました。
このロジックは output メソッドの中でやるとよいと思います

outputメソッドの仕様は
```
outputメソッドは引数に配列を取る。
ただし1件以上要素があるので、空配列を渡さないこと(呼び出し時にチェックすること)
```

というなりますが、

````
outputメソッドは引数に配列を取る。
要素数が0件の場合は出力を行わない(呼び出し時に要素数チェックは不要)
```

となる方がoutputメソッドを再利用しやすくなります

具体的にはガード構文が使えると思います
https://qiita.com/kouyan/items/7b8b456b626447a1e24e

2023-08-01 08:05 UTC, morimorihoge commented on 04.ls/ls.rb
> +def search_option
COMMENT:

こちらのメソッドですが、引数に `ARGV` を撮る用に作っておくと、このメソッド自体が独立した実装になりテストしやすくなるかなと思います。

このあたりは後のリファクタリングでやればいい話でもありますが、testableなメソッドの意識をできると、機能分割の目安になるかなあと思いました。

2023-08-01 23:19 UTC, cellotak commented on 04.ls/ls.rb
> +output(filenames) unless filenames.empty?
空フォルダ指定時の処理をoutputメソッド内に変更しました。

2023-08-01 23:19 UTC, cellotak commented on 04.ls/ls.rb
> +def search_option
引数にARGVをとれるようにしました。

2023-08-08 02:18 UTC, JunichiIto commented on 04.ls/ls.rb
> +    Dir.glob('*', base: target_path)
片方はentries + sort、もう片方はglobのみ、で対称性がなくてちょっと気持ち悪いですね。
メソッドが違うので異なるデータが返ってきそうな印象を受けます。
なるべくどちらも同じメソッドを使うように書き替えることはできますか？

2023-08-08 02:18 UTC, JunichiIto commented on 04.ls/ls.rb
> +def search_option
これ、細かいことを言うと、`parse!`で引数の内容を破壊的に変えちゃうんですよね。
OptionParserやARGVを使うなら特殊なケースなので許容範囲か、という気もするのですが、できれば非破壊的な`parse`を使って引数を変更しない方が一般的なメソッドの設計としてお行儀がいいような気がします。

[\!が付く破壊的メソッドの使用は原則として避ける \| FBC](https://bootcamp.fjord.jp/pages/do-not-use-destructive-method)

2023-08-08 02:20 UTC, JunichiIto commented on 04.ls/ls.rb
>        print target_filename.ljust(widths[col_index]) unless target_filename.nil?
```suggestion
      print target_filename&.ljust(widths[col_index])
```

でもいいかも。

2023-08-08 06:05 UTC, cellotak commented on 04.ls/ls.rb
> +    Dir.glob('*', base: target_path)
もう一度公式リファレンスを熟読したら、globでも隠しファイルをマッチさせる方法をみつけたので、globに統一しました。
また、globにはパラメーターとしてsortが用意されていたので、そちらでsortするようにしました。

2023-08-08 06:08 UTC, cellotak commented on 04.ls/ls.rb
>        print target_filename.ljust(widths[col_index]) unless target_filename.nil?
チェリー本で出てきたぼっち演算子、ここで使えたんですね！
その部分、もやもやするなと思っていましたが非常にスッキリしました。
ありがとうございます！

2023-08-08 06:43 UTC, cellotak commented on 04.ls/ls.rb
> +def search_option
下記のようにopt.parseの戻り値をローカル変数に入れて、2つまとめて戻り値にするように変更しました。受け取り先では多重代入になってます。

```ruby
  arguments_without_options = opt.parse(argv)
  return option_params, arguments_without_options
```

しかし、rubocopには一つの配列に入れるように指摘されてます。
個人的には戻り値を2つにして、受取先で多重代入する書き方の方がしっくり来たのですが、どうすべきか悩んでます。
![image](https://github.com/cellotak/ruby-practices/assets/65953037/85f0b30d-b4ee-4367-afc8-a9b5d565df08)


それとも、そもそも`search_option`メソッドの役割が2つになっているので、それを分けるべきでしょうか。
その場合、ARGVからoptionを取り出すメソッド、ARGVからoption除いてディレクトリパスを取り出すメソッド、の2つにわける方法として
1. opt.parseを2回繰り返すことを許容して、メソッドを分ける
1.  クラスを作ってインスタンス変数
といったものが考えられますが、どちらが良いと思われるでしょうか。あるいは他の案などありますでしょうか。

長くなってしまいましたがご確認お願い致します。

2023-08-09 00:32 UTC, JunichiIto reviewed
コメントしましたー。

2023-08-09 00:32 UTC, JunichiIto commented on 04.ls/ls.rb
> +  return option_params, arguments_without_options
```suggestion
  [option_params, arguments_without_options]
```

rubocopの指摘はこれで直るはずですー。

2023-08-09 00:32 UTC, JunichiIto commented on 04.ls/ls.rb
> +  arguments_without_options = opt.parse(argv)
この変数名、長い上にあまり抽象化できてないですね。。
オプションを取り除いたあとに残る情報はファイルパスになるはずなので、

```suggestion
  paths = opt.parse(argv)
```

とか

```suggestion
  file_paths = opt.parse(argv)
```

みたいな名前の方がいいと思います。

2023-08-09 00:32 UTC, JunichiIto commented on 04.ls/ls.rb
> +    Dir.glob('*', base: target_path, sort: true)
`File::FNM_DOTMATCH`以外は同じですね。
オプションなしはたしか整数の0だったと思うので、`params[:a]`の有無で第2引数を切り替えるようにして、それ以外はDRYにしたい（globを使うのは一回だけにしたい）です。

あと、sortオプションはデフォルトでtrueになってるはずなので省略してもいいかなと思いました。

2023-08-09 00:32 UTC, JunichiIto commented on 04.ls/ls.rb
> +    end
好みの問題かもしれませんが、三項演算子で1行にまとめたい。。

2023-08-09 00:32 UTC, JunichiIto commented on 04.ls/ls.rb
> +option_params, arguments_without_options = search_option(ARGV)
option_paramsはoptionなのかparamsなのか、どっちかに寄せてしまっていいと思います。
`def get_filenames(target_path, params)` の引数名と合わせる、という方針がいいかもしれません。

参考 [ユーザーを見つけたら……Aさん「自転車に入れます」Bさん「人間に入れます」Cさん「ユーザーに入れます」 \| FBC](https://bootcamp.fjord.jp/pages/readable-variable-name)

2023-08-09 02:30 UTC, cellotak commented on 04.ls/ls.rb
> +  return option_params, arguments_without_options
ありがとうございます。とりあえず配列で値を返すように変更しました。
https://github.com/cellotak/ruby-practices/pull/7#discussion_r1286663733
の後半で相談させて頂いた内容についてはいかがでしょうか。(メソッドを分けるべきかどうか)

2023-08-09 02:31 UTC, cellotak commented on 04.ls/ls.rb
> +  arguments_without_options = opt.parse(argv)
なるほど、確かに言われてみるとわかりづらい名前ですね。
変数名の付け方がまだまだだと感じます。
提案頂いた`file_paths`に変更させて頂きます。

2023-08-09 02:35 UTC, cellotak commented on 04.ls/ls.rb
> +    Dir.glob('*', base: target_path, sort: true)
> File::FNM_DOTMATCH以外は同じですね。

気付いてませんでした。globを使うのは1回だけになるよう`File::FNM_DOTMATCH`の部分を変数にしました。ここでも3項演算子が使えることに気が付いたのでスッキリさせることができました。

sortオプションについて、デフォルトの設定に気づいていませんでした。省略しました。

2023-08-09 02:36 UTC, cellotak commented on 04.ls/ls.rb
> +    end
3項演算子に変更しました。
こういった場面で使えるのですね。

2023-08-09 02:38 UTC, cellotak commented on 04.ls/ls.rb
> +option_params, arguments_without_options = search_option(ARGV)
なるほど、おっしゃるとおりその部分が統一できていませんでしたね。
`params`だとなんのパラメータかわかりづらい気がしたので、今回はコード全体を通して`options`に変更しました。

2023-08-09 08:06 UTC, ebihara-tomonari commented on 04.ls/ls.rb
> +  number_of_col = filenames.size < NUMBER_OF_COL_MAX ? filenames.size : NUMBER_OF_COL_MAX
ここ三項演算子で行数減らしちゃってますが、実は意味合い的に考えると微妙です
```ruby
number_of_col = [filenames.size, NUMBER_OF_COL_MAX].min
```
とするのが良さげです

`dotmatch_flag = options[:a] ? File::FNM_DOTMATCH : 0` この三項演算子の使い方なら良い 👌

2023-08-09 08:14 UTC, cellotak commented on 04.ls/ls.rb
> +  number_of_col = filenames.size < NUMBER_OF_COL_MAX ? filenames.size : NUMBER_OF_COL_MAX
ありがとうございます！それは目から鱗でした

2023-08-09 08:30 UTC, cellotak commented on 04.ls/ls.rb
> +    end
https://github.com/cellotak/ruby-practices/pull/7#discussion_r1288109178 のコメントを受け、二つのminを取る方法にさらに変更しました。

2023-08-10 01:18 UTC, JunichiIto reviewed
コメントしました〜。

> それとも、そもそもsearch_optionメソッドの役割が2つになっているので、それを分けるべきでしょうか。

これぐらいなら許容範囲かな〜と思います。
起動時引数を処理した結果、2つのデータを返す必要があった、という認識です。

こだわるなら、ハッシュや専用クラスを作ってそれを返す、とかですかね〜。

```ruby
def search_option(argv)
  opt = OptionParser.new
  options = {}
  opt.on('-a') { |v| options[:a] = v }
  file_paths = opt.parse(argv)
  { options: options, file_paths: file_paths }

  # もしくは
  WcArgs.new(options, file_paths)
end
```

2023-08-10 01:18 UTC, JunichiIto commented on 04.ls/ls.rb
> +options, file_paths = search_option(ARGV)
searchよりもparseの方がメソッドの役割に即しているように思います。あとoptionかoptionsかも揃えた方がベターですね。

```suggestion
options, file_paths = parse_options(ARGV)
```

2023-08-10 01:18 UTC, JunichiIto commented on 04.ls/ls.rb
> +NUMBER_OF_COL_MAX = 3
プログラミングの変数名やメソッド名ってあまりofは使われない気がします。（ゼロではないけどあまり見ない）
なので、 b_of_a みたいな変数名は a_b みたいに書いた方が馴染みが良いです。
あと、maxを使うなら、a_max よりも max_a の方が自然かも。
あとnumberは「番号」のように解釈される可能性もありそう。ここはcountとかの方がいいかな。

・・・という見解を踏まえて新しい定数の名前を考えてみてほしいです！

2023-08-10 01:18 UTC, JunichiIto commented on 04.ls/ls.rb
> +  number_of_row = ((filenames.size - 1) / NUMBER_OF_COL_MAX) + 1
ここも上の定数の指摘と同じです。

2023-08-10 01:18 UTC, JunichiIto commented on 04.ls/ls.rb
> +filenames = get_filenames(target_path, options)
Rubyって`get_`や`set_`っていうprefixはあまり使わないので（これもゼロではないです）、別の動詞を使った方がいいかも。
それこそ`search_`とか、`fetch_`とか。

あと、めっちゃ細かいんですが、 filename とto file_path でアンダーバーの使い方に一貫性がないのも気になります。。

2023-08-10 02:36 UTC, cellotak commented
> これぐらいなら許容範囲かな〜と思います。
> 起動時引数を処理した結果、2つのデータを返す必要があった、という認識です。
> こだわるなら、ハッシュや専用クラスを作ってそれを返す、とかですかね〜。

@JunichiIto 
分かりました！ここからまたロジックを書き換えるのは時間かかりすぎてしまいそうなので、今回は一旦このままで進めたいと思います。
(またlsコマンドの最後で挑戦させてもらうかもしれません。)

2023-08-10 02:37 UTC, cellotak commented on 04.ls/ls.rb
> +options, file_paths = search_option(ARGV)
searchからparseに変更しました。

optionのその部分漏れてました！そこも修正しました。

2023-08-10 02:39 UTC, cellotak commented on 04.ls/ls.rb
> +NUMBER_OF_COL_MAX = 3
命名について解説頂きありがとうございます。
「××の数」を表す変数を調べたところ、`××_count`とするパターンが多そうだったため、

`NUMBER_OF_COL_MAX` ⇒ `MAX_COL_COUNT` としてみました。

2023-08-10 02:41 UTC, cellotak commented on 04.ls/ls.rb
> +  number_of_row = ((filenames.size - 1) / NUMBER_OF_COL_MAX) + 1
同様に、
 `number_of_row` ⇒ `row_count` 
 `number_of_col`  ⇒  `col_count`
 のように変更しました。

2023-08-10 02:43 UTC, cellotak commented on 04.ls/ls.rb
> +filenames = get_filenames(target_path, options)
`fetch`の方がイメージに近いと思ったので、`fetch`に変更しました。

アンダーバーの一貫性は気づいていませんでした。
`filename`や`filenames`はアンダーバーで分けることにしました。

2023-08-10 02:49 UTC, cellotak commented on 04.ls/ls.rb
> +output(file_names)
レビューして頂いた点とは別になりますが、
元々`file_paths`としていた変数はファイルのパスではなく、「名前を表示させたいファイルがあるディレクトリのパス」が入っている状態で不自然に感じたので、`directory_paths`という風に変更しました。

また`target_path`もあくまでもディレクトリのパスなので同様に`target_directory_path`に変更しました。

2023-08-10 05:55 UTC, JunichiIto approved these changes
1点コメントしましたが、すぐに直せる問題だと思うのでこれでOKです！

2023-08-10 05:55 UTC, JunichiIto commented on 04.ls/ls.rb
> +target_directory_path = directory_paths[0] || './'
targetじゃないdirectory_pathがあるのか？と言ったらないと思うので、

```suggestion
directory_path = directory_paths[0] || './'
```

でもいいんじゃないかなーと思います。

2023-08-10 06:52 UTC, cellotak commented on 04.ls/ls.rb
> +target_directory_path = directory_paths[0] || './'
たしかにtargetじゃないものはないですね
修正しておきます！

2023-08-14 06:38 UTC, merged